<?php

namespace App\Enums;

enum CountryCode: string
{
    case AFGHANISTAN = 'AF';
    case ALBANIA = 'AL';
    case ALGERIA = 'DZ';
    case ANDORRA = 'AD';
    case ANGOLA = 'AO';
    case ARGENTINA = 'AR';
    case ARMENIA = 'AM';
    case AUSTRALIA = 'AU';
    case AUSTRIA = 'AT';
    case AZERBAIJAN = 'AZ';
    case BAHAMAS = 'BS';
    case BAHRAIN = 'BH';
    case BANGLADESH = 'BD';
    case BARBADOS = 'BB';
    case BELARUS = 'BY';
    case BELGIUM = 'BE';
    case BELIZE = 'BZ';
    case BENIN = 'BJ';
    case BHUTAN = 'BT';
    case BOLIVIA = 'BO';
    case BOSNIA_AND_HERZEGOVINA = 'BA';
    case BOTSWANA = 'BW';
    case BRAZIL = 'BR';
    case BRUNEI = 'BN';
    case BULGARIA = 'BG';
    case BURKINA_FASO = 'BF';
    case BURUNDI = 'BI';
    case CAMBODIA = 'KH';
    case CAMEROON = 'CM';
    case CANADA = 'CA';
    case CAPE_VERDE = 'CV';
    case CENTRAL_AFRICAN_REPUBLIC = 'CF';
    case CHAD = 'TD';
    case CHILE = 'CL';
    case CHINA = 'CN';
    case COLOMBIA = 'CO';
    case COMOROS = 'KM';
    case CONGO = 'CG';
    case COSTA_RICA = 'CR';
    case CROATIA = 'HR';
    case CUBA = 'CU';
    case CYPRUS = 'CY';
    case CZECH_REPUBLIC = 'CZ';
    case DENMARK = 'DK';
    case DJIBOUTI = 'DJ';
    case DOMINICA = 'DM';
    case DOMINICAN_REPUBLIC = 'DO';
    case ECUADOR = 'EC';
    case EGYPT = 'EG';
    case EL_SALVADOR = 'SV';
    case EQUATORIAL_GUINEA = 'GQ';
    case ERITREA = 'ER';
    case ESTONIA = 'EE';
    case ESWATINI = 'SZ';
    case ETHIOPIA = 'ET';
    case FIJI = 'FJ';
    case FINLAND = 'FI';
    case FRANCE = 'FR';
    case GABON = 'GA';
    case GAMBIA = 'GM';
    case GEORGIA = 'GE';
    case GERMANY = 'DE';
    case GHANA = 'GH';
    case GREECE = 'GR';
    case GRENADA = 'GD';
    case GUATEMALA = 'GT';
    case GUINEA = 'GN';
    case GUINEA_BISSAU = 'GW';
    case GUYANA = 'GY';
    case HAITI = 'HT';
    case HONDURAS = 'HN';
    case HUNGARY = 'HU';
    case ICELAND = 'IS';
    case INDIA = 'IN';
    case INDONESIA = 'ID';
    case IRAN = 'IR';
    case IRAQ = 'IQ';
    case IRELAND = 'IE';
    case ISRAEL = 'IL';
    case ITALY = 'IT';
    case JAMAICA = 'JM';
    case JAPAN = 'JP';
    case JORDAN = 'JO';
    case KAZAKHSTAN = 'KZ';
    case KENYA = 'KE';
    case KIRIBATI = 'KI';
    case KOREA_NORTH = 'KP';
    case KOREA_SOUTH = 'KR';
    case KUWAIT = 'KW';
    case KYRGYZSTAN = 'KG';
    case LAOS = 'LA';
    case LATVIA = 'LV';
    case LEBANON = 'LB';
    case LESOTHO = 'LS';
    case LIBERIA = 'LR';
    case LIBYA = 'LY';
    case LIECHTENSTEIN = 'LI';
    case LITHUANIA = 'LT';
    case LUXEMBOURG = 'LU';
    case MADAGASCAR = 'MG';
    case MALAWI = 'MW';
    case MALAYSIA = 'MY';
    case MALDIVES = 'MV';
    case MALI = 'ML';
    case MALTA = 'MT';
    case MARSHALL_ISLANDS = 'MH';
    case MAURITANIA = 'MR';
    case MAURITIUS = 'MU';
    case MEXICO = 'MX';
    case MICRONESIA = 'FM';
    case MOLDOVA = 'MD';
    case MONACO = 'MC';
    case MONGOLIA = 'MN';
    case MONTENEGRO = 'ME';
    case MOROCCO = 'MA';
    case MOZAMBIQUE = 'MZ';
    case MYANMAR = 'MM';
    case NAMIBIA = 'NA';
    case NAURU = 'NR';
    case NEPAL = 'NP';
    case NETHERLANDS = 'NL';
    case NEW_ZEALAND = 'NZ';
    case NICARAGUA = 'NI';
    case NIGER = 'NE';
    case NIGERIA = 'NG';
    case NORTH_MACEDONIA = 'MK';
    case NORWAY = 'NO';
    case OMAN = 'OM';
    case PAKISTAN = 'PK';
    case PALAU = 'PW';
    case PALESTINE = 'PS';
    case PANAMA = 'PA';
    case PAPUA_NEW_GUINEA = 'PG';
    case PARAGUAY = 'PY';
    case PERU = 'PE';
    case PHILIPPINES = 'PH';
    case POLAND = 'PL';
    case PORTUGAL = 'PT';
    case QATAR = 'QA';
    case ROMANIA = 'RO';
    case RUSSIA = 'RU';
    case RWANDA = 'RW';
    case SAINT_KITTS_AND_NEVIS = 'KN';
    case SAINT_LUCIA = 'LC';
    case SAINT_VINCENT_AND_THE_GRENADINES = 'VC';
    case SAMOA = 'WS';
    case SAN_MARINO = 'SM';
    case SAO_TOME_AND_PRINCIPE = 'ST';
    case SAUDI_ARABIA = 'SA';
    case SENEGAL = 'SN';
    case SERBIA = 'RS';
    case SEYCHELLES = 'SC';
    case SIERRA_LEONE = 'SL';
    case SINGAPORE = 'SG';
    case SLOVAKIA = 'SK';
    case SLOVENIA = 'SI';
    case SOLOMON_ISLANDS = 'SB';
    case SOMALIA = 'SO';
    case SOUTH_AFRICA = 'ZA';
    case SOUTH_SUDAN = 'SS';
    case SPAIN = 'ES';
    case SRI_LANKA = 'LK';
    case SUDAN = 'SD';
    case SURINAME = 'SR';
    case SWEDEN = 'SE';
    case SWITZERLAND = 'CH';
    case SYRIA = 'SY';
    case TAIWAN = 'TW';
    case TAJIKISTAN = 'TJ';
    case TANZANIA = 'TZ';
    case THAILAND = 'TH';
    case TIMOR_LESTE = 'TL';
    case TOGO = 'TG';
    case TONGA = 'TO';
    case TRINIDAD_AND_TOBAGO = 'TT';
    case TUNISIA = 'TN';
    case TURKEY = 'TR';
    case TURKMENISTAN = 'TM';
    case TUVALU = 'TV';
    case UGANDA = 'UG';
    case UKRAINE = 'UA';
    case UNITED_ARAB_EMIRATES = 'AE';
    case UNITED_KINGDOM = 'GB';
    case UNITED_STATES = 'US';
    case URUGUAY = 'UY';
    case UZBEKISTAN = 'UZ';
    case VANUATU = 'VU';
    case VATICAN_CITY = 'VA';
    case VENEZUELA = 'VE';
    case VIETNAM = 'VN';
    case YEMEN = 'YE';
    case ZAMBIA = 'ZM';
    case ZIMBABWE = 'ZW';

    /**
     * Get the international dialing code (phone country code) for the country
     */
    public function phoneCode(): string
    {
        return match ($this) {
            self::AFGHANISTAN => '+93',
            self::ALBANIA => '+355',
            self::ALGERIA => '+213',
            self::ANDORRA => '+376',
            self::ANGOLA => '+244',
            self::ARGENTINA => '+54',
            self::ARMENIA => '+374',
            self::AUSTRALIA => '+61',
            self::AUSTRIA => '+43',
            self::AZERBAIJAN => '+994',
            self::BAHAMAS => '+1242',
            self::BAHRAIN => '+973',
            self::BANGLADESH => '+880',
            self::BARBADOS => '+1246',
            self::BELARUS => '+375',
            self::BELGIUM => '+32',
            self::BELIZE => '+501',
            self::BENIN => '+229',
            self::BHUTAN => '+975',
            self::BOLIVIA => '+591',
            self::BOSNIA_AND_HERZEGOVINA => '+387',
            self::BOTSWANA => '+267',
            self::BRAZIL => '+55',
            self::BRUNEI => '+673',
            self::BULGARIA => '+359',
            self::BURKINA_FASO => '+226',
            self::BURUNDI => '+257',
            self::CAMBODIA => '+855',
            self::CAMEROON => '+237',
            self::CANADA => '+1',
            self::CAPE_VERDE => '+238',
            self::CENTRAL_AFRICAN_REPUBLIC => '+236',
            self::CHAD => '+235',
            self::CHILE => '+56',
            self::CHINA => '+86',
            self::COLOMBIA => '+57',
            self::COMOROS => '+269',
            self::CONGO => '+242',
            self::COSTA_RICA => '+506',
            self::CROATIA => '+385',
            self::CUBA => '+53',
            self::CYPRUS => '+357',
            self::CZECH_REPUBLIC => '+420',
            self::DENMARK => '+45',
            self::DJIBOUTI => '+253',
            self::DOMINICA => '+1767',
            self::DOMINICAN_REPUBLIC => '+1809',
            self::ECUADOR => '+593',
            self::EGYPT => '+20',
            self::EL_SALVADOR => '+503',
            self::EQUATORIAL_GUINEA => '+240',
            self::ERITREA => '+291',
            self::ESTONIA => '+372',
            self::ESWATINI => '+268',
            self::ETHIOPIA => '+251',
            self::FIJI => '+679',
            self::FINLAND => '+358',
            self::FRANCE => '+33',
            self::GABON => '+241',
            self::GAMBIA => '+220',
            self::GEORGIA => '+995',
            self::GERMANY => '+49',
            self::GHANA => '+233',
            self::GREECE => '+30',
            self::GRENADA => '+1473',
            self::GUATEMALA => '+502',
            self::GUINEA => '+224',
            self::GUINEA_BISSAU => '+245',
            self::GUYANA => '+592',
            self::HAITI => '+509',
            self::HONDURAS => '+504',
            self::HUNGARY => '+36',
            self::ICELAND => '+354',
            self::INDIA => '+91',
            self::INDONESIA => '+62',
            self::IRAN => '+98',
            self::IRAQ => '+964',
            self::IRELAND => '+353',
            self::ISRAEL => '+972',
            self::ITALY => '+39',
            self::JAMAICA => '+1876',
            self::JAPAN => '+81',
            self::JORDAN => '+962',
            self::KAZAKHSTAN => '+7',
            self::KENYA => '+254',
            self::KIRIBATI => '+686',
            self::KOREA_NORTH => '+850',
            self::KOREA_SOUTH => '+82',
            self::KUWAIT => '+965',
            self::KYRGYZSTAN => '+996',
            self::LAOS => '+856',
            self::LATVIA => '+371',
            self::LEBANON => '+961',
            self::LESOTHO => '+266',
            self::LIBERIA => '+231',
            self::LIBYA => '+218',
            self::LIECHTENSTEIN => '+423',
            self::LITHUANIA => '+370',
            self::LUXEMBOURG => '+352',
            self::MADAGASCAR => '+261',
            self::MALAWI => '+265',
            self::MALAYSIA => '+60',
            self::MALDIVES => '+960',
            self::MALI => '+223',
            self::MALTA => '+356',
            self::MARSHALL_ISLANDS => '+692',
            self::MAURITANIA => '+222',
            self::MAURITIUS => '+230',
            self::MEXICO => '+52',
            self::MICRONESIA => '+691',
            self::MOLDOVA => '+373',
            self::MONACO => '+377',
            self::MONGOLIA => '+976',
            self::MONTENEGRO => '+382',
            self::MOROCCO => '+212',
            self::MOZAMBIQUE => '+258',
            self::MYANMAR => '+95',
            self::NAMIBIA => '+264',
            self::NAURU => '+674',
            self::NEPAL => '+977',
            self::NETHERLANDS => '+31',
            self::NEW_ZEALAND => '+64',
            self::NICARAGUA => '+505',
            self::NIGER => '+227',
            self::NIGERIA => '+234',
            self::NORTH_MACEDONIA => '+389',
            self::NORWAY => '+47',
            self::OMAN => '+968',
            self::PAKISTAN => '+92',
            self::PALAU => '+680',
            self::PALESTINE => '+970',
            self::PANAMA => '+507',
            self::PAPUA_NEW_GUINEA => '+675',
            self::PARAGUAY => '+595',
            self::PERU => '+51',
            self::PHILIPPINES => '+63',
            self::POLAND => '+48',
            self::PORTUGAL => '+351',
            self::QATAR => '+974',
            self::ROMANIA => '+40',
            self::RUSSIA => '+7',
            self::RWANDA => '+250',
            self::SAINT_KITTS_AND_NEVIS => '+1869',
            self::SAINT_LUCIA => '+1758',
            self::SAINT_VINCENT_AND_THE_GRENADINES => '+1784',
            self::SAMOA => '+685',
            self::SAN_MARINO => '+378',
            self::SAO_TOME_AND_PRINCIPE => '+239',
            self::SAUDI_ARABIA => '+966',
            self::SENEGAL => '+221',
            self::SERBIA => '+381',
            self::SEYCHELLES => '+248',
            self::SIERRA_LEONE => '+232',
            self::SINGAPORE => '+65',
            self::SLOVAKIA => '+421',
            self::SLOVENIA => '+386',
            self::SOLOMON_ISLANDS => '+677',
            self::SOMALIA => '+252',
            self::SOUTH_AFRICA => '+27',
            self::SOUTH_SUDAN => '+211',
            self::SPAIN => '+34',
            self::SRI_LANKA => '+94',
            self::SUDAN => '+249',
            self::SURINAME => '+597',
            self::SWEDEN => '+46',
            self::SWITZERLAND => '+41',
            self::SYRIA => '+963',
            self::TAIWAN => '+886',
            self::TAJIKISTAN => '+992',
            self::TANZANIA => '+255',
            self::THAILAND => '+66',
            self::TIMOR_LESTE => '+670',
            self::TOGO => '+228',
            self::TONGA => '+676',
            self::TRINIDAD_AND_TOBAGO => '+1868',
            self::TUNISIA => '+216',
            self::TURKEY => '+90',
            self::TURKMENISTAN => '+993',
            self::TUVALU => '+688',
            self::UGANDA => '+256',
            self::UKRAINE => '+380',
            self::UNITED_ARAB_EMIRATES => '+971',
            self::UNITED_KINGDOM => '+44',
            self::UNITED_STATES => '+1',
            self::URUGUAY => '+598',
            self::UZBEKISTAN => '+998',
            self::VANUATU => '+678',
            self::VATICAN_CITY => '+39',
            self::VENEZUELA => '+58',
            self::VIETNAM => '+84',
            self::YEMEN => '+967',
            self::ZAMBIA => '+260',
            self::ZIMBABWE => '+263',
        };
    }
}
